/**
 * regen-index — SessionEnd hook handler and CLI command for INDEX.md generation.
 *
 * Scans ~/.claudenv/memories/decisions/ + <cwd>/.claude/memories/decisions/,
 * picks the top-N most recent by `date:` frontmatter, and produces a compact
 * INDEX.md briefing (~30-50 lines) that the next session reads via memory tool
 * or via `--append-system-prompt` (loop).
 *
 * Idempotent. Hard-capped output size so it never bloats the cache.
 */

import { readFile, writeFile, readdir, mkdir, unlink, stat } from 'node:fs/promises';
import { join, basename } from 'node:path';
import { homedir } from 'node:os';

const DEFAULT_RECENT_LIMIT = 5;
const MAX_INDEX_LINES = 60;

// Lazy resolution so tests can override via process.env.CLAUDENV_HOME.
function claudenvHome() {
  return process.env.CLAUDENV_HOME || join(homedir(), '.claudenv');
}
function memoriesDir() { return join(claudenvHome(), 'memories'); }
function globalDecisionsDir() { return join(memoriesDir(), 'decisions'); }
function userPrefsPath() { return join(memoriesDir(), 'user', 'preferences.md'); }
function indexPath() { return join(memoriesDir(), 'INDEX.md'); }
function dirtyFlagPath() { return join(claudenvHome(), '.index-dirty'); }

/**
 * Read YAML frontmatter into a flat object. Same minimal parser as decisions-logger.
 */
function parseFrontmatter(text) {
  const match = /^---\n([\s\S]*?)\n---/.exec(text);
  if (!match) return null;
  const result = {};
  for (const line of match[1].split('\n')) {
    const m = /^([a-zA-Z_][a-zA-Z0-9_-]*):\s*(.*)$/.exec(line);
    if (!m) continue;
    let value = m[2].trim().replace(/^['"]|['"]$/g, '');
    result[m[1]] = value;
  }
  return result;
}

/**
 * Collect decision entries from one directory.
 * @returns {Promise<Array<{file: string, date: string|null, topic: string, chose: string, scope: string}>>}
 */
async function collectDecisions(dir, scopeHint) {
  let names;
  try {
    names = await readdir(dir);
  } catch {
    return [];
  }
  const out = [];
  for (const name of names) {
    if (!name.endsWith('.md')) continue;
    const full = join(dir, name);
    let text;
    try {
      text = await readFile(full, 'utf-8');
    } catch {
      continue;
    }
    const fm = parseFrontmatter(text) || {};
    out.push({
      file: full,
      name,
      date: fm.date || null,
      topic: fm.topic || name.replace(/\.md$/, ''),
      chose: fm.chose || '',
      scope: fm.scope || scopeHint,
    });
  }
  return out;
}

/**
 * Read user/preferences.md, return summary lines (up to N).
 */
async function summarizePrefs(maxLines = 8) {
  try {
    const text = await readFile(userPrefsPath(), 'utf-8');
    return text
      .split('\n')
      .map((l) => l.trim())
      .filter((l) => l.startsWith('- '))
      .slice(0, maxLines);
  } catch {
    return [];
  }
}

/**
 * Generate INDEX.md content.
 *
 * @param {object} [options]
 * @param {string} [options.cwd] - Project root to include project-scoped decisions from
 * @param {number} [options.limit] - Max decisions to surface
 */
export async function regenIndex(options = {}) {
  const cwd = options.cwd || process.cwd();
  const limit = options.limit ?? DEFAULT_RECENT_LIMIT;

  const global = await collectDecisions(globalDecisionsDir(), 'global');
  const project = await collectDecisions(
    join(cwd, '.claude', 'memories', 'decisions'),
    'project'
  );

  const all = [...global, ...project];

  // Sort newest first by date (ISO sorts lexicographically). Missing date = oldest.
  all.sort((a, b) => {
    if (!a.date && !b.date) return 0;
    if (!a.date) return 1;
    if (!b.date) return -1;
    return b.date.localeCompare(a.date);
  });

  const recent = all.slice(0, limit);
  const prefs = await summarizePrefs();

  const lines = [];
  lines.push('# claudenv memory — INDEX');
  lines.push('');
  lines.push(`> Auto-generated by \`claudenv hook regen-index\`. Last: ${new Date().toISOString()}`);
  lines.push('');

  lines.push('## Recent decisions');
  lines.push('');
  if (recent.length === 0) {
    lines.push('_No decisions yet. Make a non-trivial technical choice; vibe-decisions will log it._');
  } else {
    for (const d of recent) {
      const date = d.date ? d.date.slice(0, 10) : '?';
      const scope = d.scope === 'project' ? '[project]' : '[global]';
      const slug = basename(d.name, '.md');
      lines.push(`- ${date} ${scope} **${d.topic}** → ${d.chose} (\`${slug}\`)`);
    }
  }
  lines.push('');

  if (prefs.length) {
    lines.push('## Active preferences');
    lines.push('');
    for (const p of prefs) lines.push(p);
    lines.push('');
  }

  lines.push('---');
  lines.push('');
  lines.push(`Files: ${global.length} global, ${project.length} project decisions. Run \`claudenv decisions list\` for the full set.`);

  // Hard cap to keep cache stable.
  const capped = lines.slice(0, MAX_INDEX_LINES);

  await mkdir(memoriesDir(), { recursive: true });
  await writeFile(indexPath(), capped.join('\n') + '\n', 'utf-8');

  // Clear dirty flag if present.
  try {
    await unlink(dirtyFlagPath());
  } catch {
    /* not present — fine */
  }

  return {
    indexPath: indexPath(),
    decisionCount: all.length,
    recentCount: recent.length,
  };
}

/**
 * Read the dirty flag (returns true if INDEX.md needs regen).
 */
export async function isIndexDirty() {
  try {
    await stat(dirtyFlagPath());
    return true;
  } catch {
    return false;
  }
}

/**
 * Hook entry point — called by dispatcher on SessionEnd.
 */
export async function handleRegenIndex({ event } = {}) {
  const cwd = event?.cwd || process.cwd();
  const result = await regenIndex({ cwd });
  return {
    exitCode: 0,
    message: `INDEX.md regenerated (${result.recentCount} recent of ${result.decisionCount} total decisions)`,
  };
}
