import { execSync, spawn } from 'node:child_process';
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { join } from 'node:path';
import { select } from '@inquirer/prompts';

// =============================================
// Pre-flight: check Claude CLI
// =============================================

/**
 * Check if the Claude CLI is installed and return version info.
 * @returns {{ installed: boolean, version: string|null }}
 */
export function checkClaudeCli() {
  try {
    const output = execSync('claude --version', { encoding: 'utf-8', stdio: ['pipe', 'pipe', 'pipe'] }).trim();
    return { installed: true, version: output };
  } catch {
    return { installed: false, version: null };
  }
}

// =============================================
// Spawn a single Claude invocation
// =============================================

/**
 * Spawn one `claude -p` invocation and capture JSON output.
 *
 * @param {string} prompt - The prompt to send
 * @param {object} options
 * @param {string} [options.cwd] - Working directory
 * @param {string} [options.sessionId] - Resume from session
 * @param {boolean} [options.trust] - Skip permission prompts
 * @param {string[]} [options.disallowedTools] - Tools to block
 * @param {number} [options.maxTurns] - Max agentic turns
 * @param {string} [options.model] - Model to use
 * @param {number} [options.budget] - Budget cap in USD
 * @param {string} [options.appendSystemPrompt] - Append to system prompt
 * @returns {Promise<{ result: string, sessionId: string|null, usage: object|null }>}
 */
export function spawnClaude(prompt, options = {}) {
  return new Promise((resolve, reject) => {
    const args = ['-p', prompt, '--output-format', 'json'];

    if (options.sessionId) {
      args.push('--resume', options.sessionId);
    }
    if (options.trust) {
      args.push('--dangerously-skip-permissions');
    }
    if (options.disallowedTools && options.disallowedTools.length > 0) {
      args.push('--disallowedTools', options.disallowedTools.join(','));
    }
    if (options.maxTurns) {
      args.push('--max-turns', String(options.maxTurns));
    }
    if (options.model) {
      args.push('--model', options.model);
    }
    if (options.budget) {
      args.push('--max-budget-usd', String(options.budget));
    }
    if (options.appendSystemPrompt) {
      args.push('--append-system-prompt', options.appendSystemPrompt);
    }

    const child = spawn('claude', args, {
      cwd: options.cwd || process.cwd(),
      // stdin=inherit avoids Node.js spawn hang bug, stdout=pipe to capture JSON, stderr=inherit for real-time output
      stdio: ['inherit', 'pipe', 'inherit'],
    });

    let stdout = '';

    child.stdout.on('data', (chunk) => {
      stdout += chunk.toString();
    });

    child.on('error', (err) => {
      if (err.code === 'ENOENT') {
        reject(new Error('Claude CLI not found. Install it from https://docs.anthropic.com/en/docs/claude-code'));
      } else {
        reject(err);
      }
    });

    child.on('close', (code) => {
      if (code !== 0) {
        reject(new Error(`Claude exited with code ${code}`));
        return;
      }

      try {
        const parsed = JSON.parse(stdout);
        resolve({
          result: parsed.result || '',
          sessionId: parsed.session_id || null,
          usage: parsed.usage || null,
        });
      } catch {
        // If JSON parsing fails, return raw output
        resolve({ result: stdout.trim(), sessionId: null, usage: null });
      }
    });
  });
}

// =============================================
// Internal helpers
// =============================================

/**
 * Build the planning prompt (iteration 0).
 */
function buildPlanningPrompt(goal) {
  const goalLine = goal ? `\nFocus area: ${goal}` : '';
  return `You are an expert software engineer analyzing this project to create an improvement plan.
${goalLine}

## Instructions

1. Read the project's key files: README.md, CLAUDE.md, package.json (or equivalent manifest), and 3-5 important source files.
2. Analyze the codebase for:
   - Missing test coverage
   - Code quality issues
   - Security vulnerabilities
   - Performance bottlenecks
   - Missing documentation
   - Architectural improvements
   - Developer experience improvements
3. Create a file \`.claude/improvement-plan.md\` with the following format:

\`\`\`markdown
# Improvement Plan

Generated by claudenv loop. Goal: ${goal || 'General improvement'}.

## Pending

### 1. [Title of improvement]
- **Impact**: High/Medium/Low — [why]
- **Difficulty**: High/Medium/Low
- **Files**: [files to modify]

### 2. [Title of improvement]
- **Impact**: High/Medium/Low — [why]
- **Difficulty**: High/Medium/Low
- **Files**: [files to modify]

## Completed
\`\`\`

4. Prioritize by impact (high first), then by difficulty (easy first for equal impact).
5. Include 5-10 concrete, actionable items.
6. Do NOT make any code changes in this iteration — only create the plan.
7. Commit the improvement plan: \`git add .claude/improvement-plan.md && git commit -m "Add improvement plan"\``;
}

/**
 * Build the execution prompt for iterations 1-N.
 */
function buildExecutionPrompt(iteration, maxIterations, goal) {
  const maxLine = maxIterations ? ` (iteration ${iteration} of ${maxIterations})` : ` (iteration ${iteration})`;
  const goalLine = goal ? `\nGoal: ${goal}` : '';
  return `You are an expert software engineer making improvements to this project.${maxLine}
${goalLine}

## Instructions

1. Read \`.claude/improvement-plan.md\`
2. Pick the top unfinished item from the "## Pending" section
3. Implement it:
   - Write the code changes
   - Add or update tests if applicable
   - Run tests to verify nothing is broken
4. Update \`.claude/improvement-plan.md\`:
   - Move the completed item from "## Pending" to "## Completed"
   - Add the commit hash and iteration number
   - If you discovered new issues during implementation, add them to "## Pending"
5. Commit all changes with a descriptive message
6. Report what you did in a brief summary

## Important rules

- Do NOT delete files unless the deletion IS the improvement itself
- Do NOT make changes beyond the single item you picked
- If the "## Pending" section is empty or all items are done, output exactly: NO_MORE_IMPROVEMENTS
- If you cannot complete the item (blocked, unclear, etc.), note why in the plan and pick the next item`;
}

/**
 * Check if Claude's output signals convergence (nothing left to improve).
 */
export function detectConvergence(result) {
  if (!result) return false;
  const upper = result.toUpperCase();
  return upper.includes('NO_MORE_IMPROVEMENTS') || upper.includes('NO MORE IMPROVEMENTS');
}

/**
 * Check if the loop is stuck (last 2 iterations have very similar summaries).
 */
export function detectStuck(iterations) {
  if (iterations.length < 2) return false;
  const last = iterations[iterations.length - 1].summary || '';
  const prev = iterations[iterations.length - 2].summary || '';
  if (!last || !prev) return false;

  // Simple character overlap check
  const lastLower = last.toLowerCase().trim();
  const prevLower = prev.toLowerCase().trim();
  if (lastLower === prevLower) return true;

  // Check word overlap
  const lastWords = new Set(lastLower.split(/\s+/));
  const prevWords = new Set(prevLower.split(/\s+/));
  const intersection = [...lastWords].filter((w) => prevWords.has(w));
  const union = new Set([...lastWords, ...prevWords]);
  const overlap = intersection.length / union.size;

  return overlap > 0.8;
}

/**
 * Create a git tag for the loop checkpoint.
 * @returns {string} The tag name
 */
export function createGitTag(cwd) {
  const now = new Date();
  const pad = (n) => String(n).padStart(2, '0');
  const tag = `claudenv-loop-${now.getFullYear()}-${pad(now.getMonth() + 1)}-${pad(now.getDate())}-${pad(now.getHours())}${pad(now.getMinutes())}`;
  execSync(`git tag ${tag}`, { cwd, stdio: 'pipe' });
  return tag;
}

/**
 * Find the most recent claudenv-loop-* tag.
 * @returns {string|null} Tag name or null
 */
export function getLatestLoopTag(cwd) {
  try {
    const tags = execSync('git tag -l "claudenv-loop-*" --sort=-creatordate', { cwd, encoding: 'utf-8' }).trim();
    if (!tags) return null;
    return tags.split('\n')[0];
  } catch {
    return null;
  }
}

/**
 * Read the loop log from .claude/loop-log.json.
 */
export async function readLoopLog(cwd) {
  try {
    const content = await readFile(join(cwd, '.claude', 'loop-log.json'), 'utf-8');
    return JSON.parse(content);
  } catch {
    return null;
  }
}

/**
 * Write the loop log to .claude/loop-log.json.
 */
export async function writeLoopLog(cwd, data) {
  await mkdir(join(cwd, '.claude'), { recursive: true });
  await writeFile(join(cwd, '.claude', 'loop-log.json'), JSON.stringify(data, null, 2) + '\n');
}

/**
 * Extract a brief summary from Claude's result text.
 */
function extractSummary(result) {
  if (!result) return '';
  // Take first 200 chars of the result as summary
  const clean = result.replace(/\n+/g, ' ').trim();
  return clean.length > 200 ? clean.slice(0, 200) + '...' : clean;
}

/**
 * Get the current HEAD commit hash.
 */
function getCurrentCommit(cwd) {
  try {
    return execSync('git rev-parse --short HEAD', { cwd, encoding: 'utf-8' }).trim();
  } catch {
    return null;
  }
}

/**
 * Check if git working tree is clean.
 */
function isGitClean(cwd) {
  try {
    const status = execSync('git status --porcelain', { cwd, encoding: 'utf-8' }).trim();
    return status === '';
  } catch {
    return false;
  }
}

/**
 * Print a single iteration summary.
 */
function printIterationSummary(iteration) {
  console.log(`\n  --- Iteration ${iteration.number} completed ---`);
  if (iteration.commitHash) console.log(`  Commit: ${iteration.commitHash}`);
  if (iteration.summary) console.log(`  Summary: ${iteration.summary}`);
  if (iteration.usage) {
    const { input_tokens, output_tokens } = iteration.usage;
    if (input_tokens || output_tokens) {
      console.log(`  Tokens: ${input_tokens || 0} in / ${output_tokens || 0} out`);
    }
  }
}

/**
 * Print the final loop summary.
 */
function printFinalSummary(log) {
  console.log('\n  ═══════════════════════════════════');
  console.log('  Loop complete\n');
  console.log(`  Total iterations: ${log.totalIterations}`);
  console.log(`  Stop reason: ${log.stopReason}`);
  console.log(`  Git tag: ${log.gitTag}`);
  if (log.iterations.length > 0) {
    const lastSession = log.iterations[log.iterations.length - 1].sessionId;
    if (lastSession) console.log(`  Session ID: ${lastSession} (use --resume in Claude Code)`);
  }
  console.log(`\n  To undo all changes: claudenv loop --rollback`);
  console.log('  ═══════════════════════════════════\n');
}

// =============================================
// Main loop controller
// =============================================

/**
 * Run the iterative improvement loop.
 *
 * @param {object} options
 * @param {number} [options.iterations] - Max iterations (excluding planning)
 * @param {boolean} [options.trust] - Skip permission prompts
 * @param {string} [options.goal] - Focus area
 * @param {boolean} [options.pause] - Pause between iterations
 * @param {number} [options.maxTurns] - Max turns per iteration
 * @param {string} [options.model] - Model to use
 * @param {number} [options.budget] - Budget cap per iteration
 * @param {string} [options.cwd] - Working directory
 * @param {boolean} [options.allowDirty] - Allow dirty git state
 */
export async function runLoop(options = {}) {
  const cwd = options.cwd || process.cwd();
  const maxIterations = options.iterations || Infinity;
  const pause = options.pause !== undefined ? options.pause : !options.trust;
  const disallowedTools = options.unsafe ? [] : ['Bash(rm -rf *)'];

  // --- Pre-flight: git state ---
  if (!options.allowDirty && !isGitClean(cwd)) {
    console.error('\n  Error: Git working tree is not clean.');
    console.error('  Commit or stash your changes first, or use --allow-dirty to override.\n');
    process.exit(1);
  }

  // --- Show previous loop info ---
  const prevLog = await readLoopLog(cwd);
  if (prevLog) {
    console.log(`\n  Previous loop: ${prevLog.totalIterations} iteration(s), stopped: ${prevLog.stopReason}`);
  }

  // --- Create git safety tag ---
  const preLoopCommit = getCurrentCommit(cwd);
  const gitTag = createGitTag(cwd);
  console.log(`\n  Git safety tag: ${gitTag}`);
  console.log(`  Pre-loop commit: ${preLoopCommit}`);

  // --- Initialize loop log ---
  const log = {
    started: new Date().toISOString(),
    goal: options.goal || 'General improvement',
    model: options.model || 'sonnet',
    gitTag,
    preLoopCommit,
    iterations: [],
    completedAt: null,
    stopReason: null,
    totalIterations: 0,
  };

  // --- Shared spawn options ---
  const spawnOpts = {
    cwd,
    trust: options.trust || false,
    disallowedTools,
    maxTurns: options.maxTurns || 30,
    model: options.model,
    budget: options.budget,
  };

  let sessionId = null;
  let shuttingDown = false;

  // --- Ctrl+C handling ---
  const sigintHandler = () => {
    if (shuttingDown) {
      console.log('\n  Force exit.');
      process.exit(1);
    }
    shuttingDown = true;
    console.log('\n  Graceful shutdown — waiting for current iteration to finish...');
    console.log('  Press Ctrl+C again to force exit.');
  };
  process.on('SIGINT', sigintHandler);

  try {
    // --- Iteration 0: Planning ---
    console.log('\n  Starting iteration 0 (planning)...\n');

    const planPrompt = buildPlanningPrompt(options.goal);
    const planResult = await spawnClaude(planPrompt, { ...spawnOpts, sessionId });
    sessionId = planResult.sessionId || sessionId;

    const planIteration = {
      number: 0,
      startedAt: log.started,
      completedAt: new Date().toISOString(),
      sessionId,
      summary: 'Generated improvement plan',
      commitHash: getCurrentCommit(cwd),
      usage: planResult.usage,
    };
    log.iterations.push(planIteration);
    printIterationSummary(planIteration);
    await writeLoopLog(cwd, log);

    if (shuttingDown) {
      log.stopReason = 'interrupted';
      log.completedAt = new Date().toISOString();
      log.totalIterations = 0;
      await writeLoopLog(cwd, log);
      printFinalSummary(log);
      return;
    }

    // --- Execution iterations 1-N ---
    for (let i = 1; i <= maxIterations; i++) {
      if (shuttingDown) break;

      // --- Pause between iterations ---
      if (pause && i > 1) {
        const pendingCount = await countPendingItems(cwd);
        console.log(`  Plan: ${pendingCount} item(s) remaining\n`);

        const action = await select({
          message: 'Next action:',
          choices: [
            { name: 'Continue to next iteration', value: 'continue' },
            { name: 'Edit improvement plan', value: 'edit' },
            { name: 'Change goal and continue', value: 'goal' },
            { name: 'Stop here', value: 'stop' },
          ],
        });

        if (action === 'stop') {
          log.stopReason = 'user_stopped';
          break;
        }
        if (action === 'edit') {
          console.log('\n  Edit .claude/improvement-plan.md in your editor, then press Enter to continue.');
          await select({
            message: 'Ready?',
            choices: [
              { name: 'Continue', value: 'continue' },
              { name: 'Stop', value: 'stop' },
            ],
          });
        }
        // 'goal' and 'continue' both continue
      }

      console.log(`\n  Starting iteration ${i}${maxIterations < Infinity ? ` of ${maxIterations}` : ''}...\n`);

      const startedAt = new Date().toISOString();
      const execPrompt = buildExecutionPrompt(i, maxIterations < Infinity ? maxIterations : null, options.goal);

      let iterResult;
      try {
        iterResult = await spawnClaude(execPrompt, { ...spawnOpts, sessionId });
      } catch (err) {
        console.error(`\n  Iteration ${i} failed: ${err.message}`);
        log.stopReason = 'error';
        break;
      }

      sessionId = iterResult.sessionId || sessionId;

      const iteration = {
        number: i,
        startedAt,
        completedAt: new Date().toISOString(),
        sessionId,
        summary: extractSummary(iterResult.result),
        commitHash: getCurrentCommit(cwd),
        usage: iterResult.usage,
      };
      log.iterations.push(iteration);
      log.totalIterations = i;
      printIterationSummary(iteration);
      await writeLoopLog(cwd, log);

      // --- Convergence check ---
      if (detectConvergence(iterResult.result)) {
        console.log('\n  All improvements completed.');
        log.stopReason = 'converged';
        break;
      }

      // --- Stuck detection ---
      if (detectStuck(log.iterations)) {
        console.log('\n  Warning: Loop appears stuck (similar output for 2 consecutive iterations).');
        if (!pause) {
          log.stopReason = 'stuck';
          break;
        }
        const action = await select({
          message: 'The loop appears stuck. What would you like to do?',
          choices: [
            { name: 'Continue anyway', value: 'continue' },
            { name: 'Stop here', value: 'stop' },
          ],
        });
        if (action === 'stop') {
          log.stopReason = 'stuck';
          break;
        }
      }

      // --- Check if max iterations reached ---
      if (i >= maxIterations) {
        log.stopReason = 'max_iterations';
      }
    }

    // --- Finalize ---
    if (!log.stopReason) {
      log.stopReason = shuttingDown ? 'interrupted' : 'max_iterations';
    }
  } finally {
    process.removeListener('SIGINT', sigintHandler);
  }

  log.completedAt = new Date().toISOString();
  await writeLoopLog(cwd, log);
  printFinalSummary(log);
}

/**
 * Count pending items in the improvement plan.
 */
async function countPendingItems(cwd) {
  try {
    const content = await readFile(join(cwd, '.claude', 'improvement-plan.md'), 'utf-8');
    const pendingSection = content.split('## Completed')[0].split('## Pending')[1] || '';
    const matches = pendingSection.match(/^### /gm);
    return matches ? matches.length : 0;
  } catch {
    return 0;
  }
}

// =============================================
// Rollback
// =============================================

/**
 * Rollback to the most recent claudenv-loop-* tag.
 */
export async function rollback(options = {}) {
  const cwd = options.cwd || process.cwd();

  // Try to find tag from loop log first, then from git
  const log = await readLoopLog(cwd);
  const tag = (log && log.gitTag) || getLatestLoopTag(cwd);

  if (!tag) {
    console.error('\n  No claudenv-loop tag found. Nothing to rollback.\n');
    process.exit(1);
  }

  console.log(`\n  Rolling back to tag: ${tag}`);
  console.log(`  This will discard all changes made after this tag.\n`);

  if (!options.force) {
    const action = await select({
      message: 'Are you sure?',
      choices: [
        { name: 'Yes, rollback', value: 'yes' },
        { name: 'Cancel', value: 'cancel' },
      ],
    });
    if (action === 'cancel') {
      console.log('  Cancelled.\n');
      return;
    }
  }

  execSync(`git reset --hard ${tag}`, { cwd, stdio: 'inherit' });
  execSync(`git tag -d ${tag}`, { cwd, stdio: 'inherit' });

  console.log('\n  Rollback complete. All loop changes have been undone.\n');
}
