/**
 * CLI: `claudenv memory init/index/show/edit`
 *
 * Owns the user-facing surface for the global ~/.claudenv/memories/ layout.
 * Reuses regen-index for `index` so there's one canonical regeneration path.
 */

import { mkdir, readFile, writeFile, stat } from 'node:fs/promises';
import { join, dirname, resolve } from 'node:path';
import { spawnSync } from 'node:child_process';
import {
  claudenvHome,
  memoriesDir,
  globalDecisionsDir,
  canonIndexPath,
  userPrefsPath,
  indexMdPath,
} from './memory-paths.js';
import { regenIndex } from './hooks/regen-index.js';

/**
 * `claudenv memory init` — create the global memory layout if absent.
 * Idempotent; never overwrites existing files.
 */
export async function memoryInit() {
  const created = [];
  const skipped = [];

  // Layout
  const dirs = [
    memoriesDir(),
    globalDecisionsDir(),
    join(memoriesDir(), 'canon'),
    join(memoriesDir(), 'user'),
  ];
  for (const d of dirs) {
    await mkdir(d, { recursive: true });
  }

  // Seed files
  const seeds = [
    {
      path: indexMdPath(),
      content:
        '# claudenv memory — INDEX\n\n> Auto-generated by `claudenv memory index`. Hand-edits will be overwritten.\n\n## Recent decisions\n\n_No decisions yet — vibe-decisions will log here._\n',
    },
    {
      path: canonIndexPath(),
      content:
        '# Личный канон. Добавляйте через: claudenv canon add <topic> <url> --why "<reason>"\n',
    },
    {
      path: join(claudenvHome(), '.gitignore'),
      content: 'sessions/\n*.log\n.log/\nkeys/private*\n*.local.*\n*.secret.*\n',
    },
  ];

  for (const { path, content } of seeds) {
    try {
      await stat(path);
      skipped.push(path);
    } catch {
      await mkdir(dirname(path), { recursive: true });
      await writeFile(path, content, 'utf-8');
      created.push(path);
    }
  }

  return { created, skipped };
}

/**
 * `claudenv memory index` — regenerate INDEX.md from current decisions + prefs.
 */
export async function memoryIndex({ cwd } = {}) {
  return await regenIndex({ cwd: cwd || process.cwd() });
}

/**
 * `claudenv memory show <relpath>` — print a file from memories/.
 * Path is interpreted relative to ~/.claudenv/memories/.
 */
export async function memoryShow(relPath) {
  if (!relPath) throw new Error('Usage: claudenv memory show <path>');
  const full = resolve(memoriesDir(), relPath);
  if (!full.startsWith(memoriesDir())) {
    throw new Error('Path escapes memories root');
  }
  return await readFile(full, 'utf-8');
}

/**
 * `claudenv memory edit <relpath>` — open a memory file in $EDITOR (or vi).
 * Creates the file if missing.
 */
export async function memoryEdit(relPath) {
  if (!relPath) throw new Error('Usage: claudenv memory edit <path>');
  const full = resolve(memoriesDir(), relPath);
  if (!full.startsWith(memoriesDir())) {
    throw new Error('Path escapes memories root');
  }
  await mkdir(dirname(full), { recursive: true });
  try {
    await stat(full);
  } catch {
    await writeFile(full, '', 'utf-8');
  }
  const editor = process.env.EDITOR || 'vi';
  const result = spawnSync(editor, [full], { stdio: 'inherit' });
  return { path: full, exitCode: result.status ?? 0 };
}
